from panda3d.core import *

def create_materials():
    materials = []

    default_material = Material('default_material')
    default_material.setBaseColor((1, 1, 1, 1))
    default_material.setRoughness(1.7879559993743896)
    default_material.setMetallic(False)
    default_material.setRefractiveIndex(1.5)
    materials.append(default_material)

    metal = Material("metal")
    metal.setBaseColor((0.8, 0.8, 0.8, 1))
    metal.setRoughness(0.)
    metal.setMetallic(True)
    default_material.setRefractiveIndex(1.5)
    materials.append(metal)

    mtl = Material("0")
    mtl.setBaseColor((0.662, 0.655, 0.634, 1))
    mtl.setRoughness(0.487271)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0.896, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("1")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(0.2)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("2")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(1)
    mtl.setMetallic(False)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("3")
    mtl.setBaseColor((0.66, 0.609, 0.526, 1))
    mtl.setRoughness(0.535197)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("4")
    mtl.setBaseColor((0.55, 0.556, 0.554, 1))
    mtl.setRoughness(0.540132)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("5")
    mtl.setBaseColor((0.55, 0.57, 0.58, 1))
    mtl.setRoughness(0.505592)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("6")
    mtl.setBaseColor((0.913, 0.921, 0.925, 1))
    mtl.setRoughness(0.345455)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0.821333, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("7")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(0)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("8")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(0.1)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)

    mtl = Material("9")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(0.4)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)    

    mtl = Material("10")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(0.6)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)   

    mtl = Material("11")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(1)
    mtl.setMetallic(False)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)   

    mtl = Material("12")
    mtl.setBaseColor((0.542, 0.497, 0.449, 1))
    mtl.setRoughness(0.510526)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("13")
    mtl.setBaseColor((0.955, 0.637, 0.538, 1))
    mtl.setRoughness(0.526151)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0.874667, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)    

    mtl = Material("14")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(1)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl) 

    mtl = Material("15")
    mtl.setBaseColor((0.672, 0.637, 0.585, 1))
    mtl.setRoughness(0.522039)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl) 

    mtl = Material("16")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(0.4)
    mtl.setMetallic(False)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)    

    mtl = Material("17")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(1)
    mtl.setMetallic(False)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)   

    mtl = Material("18")
    mtl.setBaseColor((0.8, 0.8, 0.8, 1))
    mtl.setRoughness(1)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)   

    mtl = Material("19")
    mtl.setBaseColor((0.972, 0.96, 0.915, 1))
    mtl.setRoughness(0.172934)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)  

    mtl = Material("20")
    mtl.setBaseColor((1, 0.766, 0.336, 1))
    mtl.setRoughness(0.410537)
    mtl.setMetallic(True)
    mtl.set_emission((0, 0, 0, 0))
    mtl.setRefractiveIndex(1.5)
    materials.append(mtl)   

    return materials



